### PR TITLE
Bubble sort

### PR DESCRIPTION
**Pull request by Rakhisharma**

### CODE REVIEW

**Comment by iamneha** [comment]
@aktech @CuriousLearner review it

**Comment by CuriousLearner** [comment]
As far as I see, you've just put a gif. How far would it actually solve the purpose of visualization? 

How would you extend this application with custom user input and controllers? What do you do when you implement another algorithm? (Put another gif?)

Let us know. @Rakhisharma @iamneha

**Comment by Rakhisharma** [comment]
@CuriousLearner hi! This is just an Idea we proposed.  And yes we were thinking about putting another gif for other algorithms. With advance feature like making gif of two different algos and comparing them on same page. So user can easily understand the difference. something similar to this https://blog.penjee.com/wp-content/uploads/2015/04/binary-and-linear-search-animations.gif  .Visualization is also an good idea and we love to work on that too. We got this idea so just proposed it in front of you all. Let us know your's view. thanks :)

**Comment by CuriousLearner** [comment]
I think if we go with gifs then it is really not necessary to run flask in the back-end. And this is certainly not what we want. I do agree that gifs can serve the purpose, but the problem we're trying to solve here is a little different.

IMO, we cannot enable user to enter custom value in gif, nor can user control the speed with which the algorithm is implemented.

cc @aktech Would you like to guide @Rakhisharma @iamneha

**Comment by aktech** [comment]
@Rakhisharma @iamneha 

I agree with @CuriousLearner. The goal is to create an interface for creating visualizations for various Algorithms & DS, whereas there isn't any customization possible in gifs as @CuriousLearner already mentioned. Please note that, two people cannot create all possible visualizations in 3 months, so its very important to create a robust framework which can be extended by people willing to contribute to the project in future and add their own custom visualizations.

**Comment by Rakhisharma** [comment]
@aktech @CuriousLearner ok, Thanks. We are working on visualization and will soon send another  PR for that. Closing this PR.

**Pull request closed without merging**
